src/video_manolo/controller/PeliculaController.java
package video_manolo.controller;

import video_manolo.entity.PeliculaEntity;
import video_manolo.facade.PeliculaLocal;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.io.Serializable;
import java.util.Collection;

/**
 * Created by chamanx on 25/08/14.
 */
@ManagedBean(name="peliculaController")
@RequestScoped
public class PeliculaController implements Serializable{
    @EJB
    private PeliculaLocal peliculaEJB;


    protected PeliculaLocal getFacade(){
        return peliculaEJB;
    }

    public Collection<PeliculaEntity> getListAll(){
        return getFacade().findAll();
    }

}

web/pelicula/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>PeliculaEntity List</title>
    </head>
    <body>
        <f:view>
            <h1>PeliculaEntity List</h1>
            <h:form>
              <!--h:commandButton action="{peliculaEntity.startCreate}" value="Create"/-->

              <p:dataTable value='#{peliculaController.listAll}' var='pelicula' >
                  <p:column>
                      <h:outputText value="#{pelicula.titulo}" />
                  </p:column>
              </p:dataTable>
            </h:form>
        </f:view>
    </body>
</html>